--
-- PostgreSQL database dump
--

\restrict 0YQTXC9aRjWho6Q7dGdd01Jgp024BSOnS5a3hSHc2utfRNOH6VoYpyQZ3BteOtu

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_sessions (
    id bigint NOT NULL,
    duration_seconds bigint,
    end_time timestamp(6) without time zone,
    start_time timestamp(6) without time zone,
    target_combination character varying(255),
    player_id bigint NOT NULL
);


ALTER TABLE public.game_sessions OWNER TO postgres;

--
-- Name: game_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.game_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.players (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.players OWNER TO postgres;

--
-- Name: players_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: targets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.targets (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    sprite_key character varying(255) NOT NULL
);


ALTER TABLE public.targets OWNER TO postgres;

--
-- Name: targets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.targets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.targets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: game_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.game_sessions (id, duration_seconds, end_time, start_time, target_combination, player_id) FROM stdin;
1	120	2026-04-15 18:57:51.790006	2026-04-15 18:57:08.643761	2,4,5	1
2	\N	\N	2026-05-04 12:11:04.788204	2,4,3	1
3	\N	\N	2026-05-04 12:11:46.510969	4,2,5	1
4	23	2026-05-04 12:14:42.219216	2026-05-04 12:14:19.09023	2,4,3	1
5	55	2026-05-04 12:27:37.277542	2026-05-04 12:26:41.910409	1,5,4	1
6	\N	\N	2026-05-04 12:36:18.091714	4,1,3	7
7	\N	\N	2026-05-05 14:01:11.877746	1,4,5	1
8	57	2026-05-05 14:02:29.451673	2026-05-05 14:01:32.000184	5,1,4	8
\.


--
-- Data for Name: players; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.players (id, password, username) FROM stdin;
1	123456	eugenia
7	123456	huwaida
8	123456	yujin
\.


--
-- Data for Name: targets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.targets (id, name, role, sprite_key) FROM stdin;
1	Mr. Astha	dosen	astha
2	Mrs. Riri	dosen	riri
3	BN	aslab	bn
4	NL	aslab	nl
5	AF	aslab	af
\.


--
-- Name: game_sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.game_sessions_id_seq', 8, true);


--
-- Name: players_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.players_id_seq', 8, true);


--
-- Name: targets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.targets_id_seq', 5, true);


--
-- Name: game_sessions game_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_sessions
    ADD CONSTRAINT game_sessions_pkey PRIMARY KEY (id);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);


--
-- Name: targets targets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.targets
    ADD CONSTRAINT targets_pkey PRIMARY KEY (id);


--
-- Name: players ukp1chj5w2v1nune5xmmd94u1yj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT ukp1chj5w2v1nune5xmmd94u1yj UNIQUE (username);


--
-- Name: game_sessions fkg7qtar0m0j6ar26ri4xl0kbah; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_sessions
    ADD CONSTRAINT fkg7qtar0m0j6ar26ri4xl0kbah FOREIGN KEY (player_id) REFERENCES public.players(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 0YQTXC9aRjWho6Q7dGdd01Jgp024BSOnS5a3hSHc2utfRNOH6VoYpyQZ3BteOtu

